export const SET_SIDEBAR_EXPAND = 'SET_SIDEBAR_EXPAND';
export type SET_SIDEBAR_EXPAND = typeof SET_SIDEBAR_EXPAND;

export const SET_RIGHT_SIDEBAR_EXPAND = 'SET_RIGHT_SIDEBAR_EXPAND';
export type SET_RIGHT_SIDEBAR_EXPAND = typeof SET_RIGHT_SIDEBAR_EXPAND;

export const RIGHT_SIDEBAR_TOGGLE = 'RIGHT_SIDEBAR_TOGGLE';
export type RIGHT_SIDEBAR_TOGGLE = typeof RIGHT_SIDEBAR_TOGGLE;

export const SET_LEFT_SIDEBAR_EXPAND = 'SET_LEFT_SIDEBAR_EXPAND';
export type SET_LEFT_SIDEBAR_EXPAND = typeof SET_LEFT_SIDEBAR_EXPAND;

export const LEFT_SIDEBAR_TOGGLE = 'LEFT_SIDEBAR_TOGGLE';
export type LEFT_SIDEBAR_TOGGLE = typeof LEFT_SIDEBAR_TOGGLE;
