export const SET_FLOATING_BUTTON_ACTIVE = 'SET_FLOATING_BUTTON_ACTIVE';
export const SET_FLOATING_BUTTON_DEACTIVE = 'SET_FLOATING_BUTTON_DEACTIVE';
export const SET_FLOATING_BUTTON_TARGET = 'SET_FLOATING_BUTTON_TARGET';
export const SET_SIDEBAR_EXPAND = 'SET_SIDEBAR_EXPAND';
export const SET_RIGHT_SIDEBAR_EXPAND = 'SET_RIGHT_SIDEBAR_EXPAND';
export const RIGHT_SIDEBAR_TOGGLE = 'RIGHT_SIDEBAR_TOGGLE';
export const LEFT_SIDEBAR_EXPAND = 'LEFT_SIDEBAR_EXPAND';
export const LEFT_SIDEBAR_TOGGLE = 'LEFT_SIDEBAR_TOGGLE';
