export const SET_LOCALE_START = 'SET_LOCALE_START';
export type SET_LOCALE_START = typeof SET_LOCALE_START;

export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export type SET_LOCALE_SUCCESS = typeof SET_LOCALE_SUCCESS;

export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';
export type SET_LOCALE_ERROR = typeof SET_LOCALE_ERROR;
